package com.cin.cyclerentalservice.vo;

public enum ReportType {
	DAY_WISE_HIGHEST_DIST_TRAVELLER,
	OVERALL_HIGHEST_DIST_TRAVELLER,
	DAY_WISE_EARLY_TRAVELLER,
	OVERALL_EARLY_TRAVELLER,
	ONE_WHO_TRAVELLED_LONGEST_TIME
}
